### PR TITLE
Add support for align attribute.

### PR DESCRIPTION
**Pull request by gfaugere**
Hi again!
This add supports for the `align` attribute which is native Quill.

I thought about adding an $ignore flag (like you did [here](https://github.com/nadar/quill-delta-parser/blob/master/src/listener/Font.php#L20) for fonts) - but could not reproduce a case where alignment was disabled and copy/pasting would create aligned content.

As with the last PRs, let me know what you think :)

### CODE REVIEW

**Comment by nadar** [comment]
Hey @gfaugere - thanks for helping make the parser better!

Isn't this something which the paragraph block listener should contain?  https://github.com/nadar/quill-delta-parser/blob/master/src/listener/Text.php

or it contains a special syntax? Or where is the difference?

(will take a closer look at the documentation later, but also want to give you feedback as soon as possible)

**Comment by gfaugere** [comment]
Not sure - the paragraph block listener seemed to be built to handle only "vanilla" inserts (with a check to make sure they have no attributes).
The align attribute only adds the text-align style, so I thought an other block listener would be appropriate. I can give a go at modifying the Text class if that is more appropriate!

**Comment by nadar** [comment]
Good catch. As you can see how complex it can be to handle proper paragraphs, maybe it should be part of the Text listener. What do you think?

@lode maybe also has some thoughts? 😃

**Comment by lode** [comment]
Both things sound correct. As in this should for sure be its own block level listener I think, there is conceptually no real difference between this one and the header listener for example. It is block level content with a specific html around it, whether that html is `<h1>` or `<p class="text-align: center;">` doesn't matter for the code.

And indeed, the code currently needed to properly handle newlines is really hard. But it also seems like something we can abstract away quite easily, there's only a few bits changing.

**Comment by gfaugere** [comment]
Will do, waiting for #32 which will indeed make this more straightforward :)

**Comment by nadar** [comment]
Yes indeed. Thanks for all the help!

**Comment by nadar** [comment]
(btw hopefully you have applied for https://hacktoberfest.digitalocean.com and can collect your shirt with those PRs you have made!)

**Comment by gfaugere** [comment]
(I would like to say that I would have contributed without hacktoberfest - but that'd be lying to myself. I probably would've made the changes in a worse way on my local copy. Guess I need to thank Digital Ocean for making me a better dev 😊)

**Comment by nadar** [comment]
The new `wrapElement` method is ready to use in the master branch

**Comment by gfaugere** [comment]
Cheers, I'll update this tomorrow!

**Pull request merged**
