### PR TITLE
Add newlines after block level elements

### PR DESCRIPTION
**Pull request by lode**
This adds a newline after every paragraph and other block level element.

My use case is that in some context's I strip the html but want to keep somewhat readable and parseable text. The newlines keep it somewhat readable, and also allow me to use `nl2br()` to make it readable in html contexts. Also I have a context where I want to show the first paragraph of text from the deltas, and since the newlines are kept I can split on the first newline.

I can imagine this use case is not super common. But adding the newlines felt like a small non-breaking addition anyway. What do you think?

The most annoying part is that tests have to be more specific. Or we have to auto-remove newlines not only from the resulting html, but also from the fixtures.

### CODE REVIEW

**Comment by nadar** [comment]
hi @lode, thanks for that PR. Why not make a new lexer property `$pretty=false` which is disabled by default, so we don't have to adjust tests?

**Comment by lode** [comment]
A little tricky is that `BlockListener->wrapElement()` doesn't have access to the Lexer. We would need to adjust that, or pass the lexer from all listeners; potentially breaking BC and not fixing custom listeners people made.

If we just care about the tests I think we can strip newlines from fixtures.

If we care about an opt-in for changing output, then we probably need to pass the lexer to BlockListener.

I feel most for fixing the tests only, and not care about the output change; that doesn't feel like breaking BC since we don't promise a certain contract.

**Comment by lode** [comment]
I've pushed commits to do a cleaner variant of changes to the tests. Feels good to me.

But the question about whether we're okay with the changed output remains.

**Comment by nadar** [comment]
I don't like it, but I can live with it. Please add a changelog.

**Review by nadar — CHANGES_REQUESTED** [review]
Add changelog

**Comment by lode** [comment]
> Add changelog

Yes, done!

**Review by nadar — APPROVED** [review]

**Pull request merged**
