### PR TITLE
Abstract simple block level rendering

### PR DESCRIPTION
**Pull request by lode**
This makes it easier to add new block level listeners, as discussed in https://github.com/nadar/quill-delta-parser/pull/31.

Currently mainly a prototype. It does pass all tests so we could just continue after doing a little CS here and there. But I think it would be good to add some more tests. And to see if we can bring other block level renders, e.g. blockquote, to the same code. (I've tried blockquote and it already works, which is slightly worrysome because the current code is different, I just want to add tests to check whether it doesn't break things in unexpected ways.)

And of course it would be great to see what is the core differences from other blocklevel renderers and whether this abstraction should also use part of the code in the text renderer.

### CODE REVIEW

**Comment by nadar** [comment]
@lode good one, looks good to me! i will adjust the code a little to make it more consistent. Thanks!

**Comment by lode** [comment]
Nice!

I've adjusted the Blockquote listener as well using changes done in https://github.com/nadar/quill-delta-parser/pull/15 and https://github.com/nadar/quill-delta-parser/pull/26. Though I couldn't find breaking tests after adding the test changes but before adjusting the listener, so that's still a bit weird.

**Comment by nadar** [comment]
and i forgot to mention that there is only a changelog entry missing.

**Comment by lode** [comment]
> and i forgot to mention that there is only a changelog entry missing, but i will do it if you like.

Yeah, didn't get to it because I wanted to flesh out the way of approaching the issue.

> Maybe we could use `__buffer__` instead of `_buffer`.

Yes. I'll change.

> Looks good. I just saw its `renderWithSimpleWarpper` should be `renderWithSimpleWrapper`. Maybe we can find a more clear name like `wrapContent` or `wrapElement` or `elementWrapper` or `contentWrapper`.
> 
> or what it really does, it generetes the line output:
> 
> `lineOutputWrapper()` or `wrapLineOutput`
> 
> What do you think?

Yeah, was struggling with this as well. What I find hard about the suggestions is that they give me the feeling that they return something, and that they only do part of the job. I would like it to be a method which (apart from some custom validation upfront) takes over the whole render job. The real rendering is just to complex to want to think about when you just want to wrap some content. In another way we could also do something like this:

```
class Blockquote implements Blocklistener {
    use SimpleWrappingRenderer;
    public function getWrapper() { return '<blockquote>{_buffer}</blockquote>'; }
}
```

Where `trait SimpleWrappingRenderer` implements the `render` method required by the interface. (Not really a fan of traits, but it makes for the clearest example.)

Or maybe `Blocklistener` just implements this as its default `render()` method, and some listeners can decide to have their own logic. Although we'd get into short term trouble of having to make something like `getWrapper()` a required method..

I think we could offer multiple of these renderers. For example lists need one where you have a wrapper at the beginning and end of the whole buffer, and a wrapper per line.

I don't really know yet where to take this yet. Also not sure if we should let the text-align PR wait on this one, this PR can also be second. I think it is good to think a bit more about the direction.

You know the possible renderings a bit better I think, does this braindump above make sense?

**Comment by nadar** [comment]
i think i understand what you mean. As for the current setup, a trait would make the most sense, but if we want to improve this in general we might go event further and introduce 3.0 which allows us to break things. But for now: let's go with your method and we might think of how to generally improve this in future.

Maybe this is also very close to a very basic "template engine" which can handles foreaches.

+ text: `<p>{{buffer}}≤/p>`
+ blockquote: `<blockquote>{{buffer}}</blockquote>`
+ heading: `<h{{option.heading}}>{{buffer}}</h{{option.heading}}>`
+ list: `<ul>{{foreach}}<li>{{buffer}}</li>{{endforeach}}</ul>`

this way the listenere could have an abstract required method `getTemplate()`and the logic of the trait can be used to generate the template variables, while `{{buffer}}` always exists.

+ abstract class Listener: `{{ buffer }}` exists <= block quote, text, ...
+ abstract class ForEachListenere: `{{ foreach }}` and `{{ buffer }}` exists. <= lists

This might also work for inline listeneres:

+ Bold: `<b>{{ buffer }}≤/b>`
+ Italic: `<i>{{ buffer }}</i>`

**Comment by nadar** [comment]
@lode shall i make the issue about further improvement and make a changelog so we can merge?

**Comment by lode** [comment]
Sorry, was pondering and forgot to come back.

I'm unsure if the current PR is a good thing actually. The template engine idea gives me the feeling we want too much from this. In my own project I have custom listeners which use Twig to render the output. And I like that I can choose to use Twig for it, and someone else can use another renderer.

Maybe a method to collect the buffer is enough. And other methods to better deal with parsed deltas at a higher level. That way gives more power to custom listeners.

If we just merge this and improve it later we have to keep this method as it can be used by other custom listeners, or cause BC breaking.

What do you feel?

**Comment by nadar** [comment]
I would rename it to `wrapElement` and merge. BC breaks is nothing bad, if we release version 3.0 this might happen and an Upgrade instruction will be posted.

The alternative would be to discard this PR, which would be the worst solution as it might by very helpfull for others when creating block listeners. Also to globalize and ensure the basic behavior works for all the listeners the same way. So if we improve the mechanism of `wrapElement` everyone profits.

**Comment by lode** [comment]
Okay, sounds good. Do you have time to make those changes and merge? (Otherwise I can do it, but it will probably be this weekend.)

**Pull request merged**
